Update Limits Default Schedule of every hour
pitt-crc/keystone-api pull request #283
Opened 2024-05-10 14:31 UTC by Comeani

resolves #282

2024-05-10 20:07 UTC, djperrefort requested changes

2024-05-10 20:07 UTC, djperrefort commented on keystone_api/apps/users/admin.py
> +    search_fields = ['name']
Duplicate of line 48. See PR #278

2024-05-13 13:27 UTC, Comeani commented on keystone_api/apps/users/admin.py
> +    search_fields = ['name']
This should be fixed now

2024-05-13 16:05 UTC, djperrefort approved these changes

2024-05-13 16:05 UTC, merged